### ISSUE TITLE
Remove duplicate fixes in IDE

### ISSUE THREAD

**Issue by marcind** [xunit/xunit.analyzers#15]
At the moment for each rule analyzer there is one fixer class (which provides 1 or more fix options). There are a number of fixes (e.g. "Convert to Fact") that apply to multiple rule violations (e.g "Theory should have parameters" and "Theory should have Data attributes"). At the moment when two such violations occur in the same code line, the "Convert to Fact" fix is provided twice.

The 1-1 mapping of analyzer-fixer should be broken. Instead, there should be 1 fixer per fix, with each fixer handling one or more rule violations. This way multiple violations can be resolve with a single action.

**Comment by bradwilson** [comment]
This issue was moved to xunit/xunit#1246
