### ISSUE TITLE
Refactoring to fix improper usage of Assert.Throws with async code

### ISSUE THREAD

**Issue by marcind** [xunit/xunit.analyzers#21]
Instead of 

``` CSharp
Assert.Throws(() => SomethingAsync());
```

do

``` CSharp
await Assert.ThrowsAsync(() => SomethingAsync());
```
- Including the overload with `paramName` parameter
- Make test method async if it's not already
- Make sure to deal with async lambdas too

**Comment by bradwilson** [comment]
This issue was moved to xunit/xunit#1248
