### ISSUE TITLE
Analyzer for child test classes rerunning tests from base type

### ISSUE THREAD

**Issue by marcind** [xunit/xunit.analyzers#26]
The following should be a warning

``` CSharp
public class Base {
  [Fact] public void Test() {}

  public class Derived : Base {
    [Fact] public void DerviedTest() {}
  }
}
```

This would cause `Test()` to be invoked twice, which is probably not what the author intended.
If base is abstract then this should not be a warning.

**Comment by bradwilson** [comment]
This issue was moved to xunit/xunit#1250
