### ISSUE TITLE
Implement scoring for how "literal" an expression is

### ISSUE THREAD

**Issue by marcind** [xunit/xunit.analyzers#27]
Rule [xUnit2000](https://github.com/marcind/xunit.analyzers/blob/master/src/xunit.analyzers/AssertEqualLiteralValueShouldBeFirst.cs) has logic for determining whether an expression is a "literal". Change the logic to implement a scoring mechanism. Something like the following (most "literal" first)
1. `null`, Literal Expressions, `typeof`, `nameof`, `sizeof`, `default`, enum values
2. Consts and static read-only fields/properties (include reference types or not?)
3. New "instances" of structs
4. Certain factory methods on structs (e.g. [DateTime.Parse](https://msdn.microsoft.com/en-us/library/system.datetime.parse.aspx))
5. Everything else.

If the second arg has a lower score than the first arg, trigger the rule.

**Comment by bradwilson** [comment]
This issue was moved to xunit/xunit#1251
