### ISSUE TITLE
Analyzer/fix for Assert.Equal/NotEqual used for collection size checks

### ISSUE THREAD

**Issue by marcind** [xunit/xunit.analyzers#28]
`Assert.Equal(0, collection.Count)` -> `Assert.Empty(collection)`
`Assert.Equal(1, collection.Count)` -> `Assert.Single(collection)`
`Assert.NotEqual(0, collection.Count)` -> `Assert.NotEmpty(collection)`

**Comment by bradwilson** [comment]
This issue was moved to xunit/xunit#1252
