### ISSUE TITLE
Analyzer for Assert.True/False used for substring matching assertions

### ISSUE THREAD

**Issue by marcind** [xunit/xunit.analyzers#39]
`Assert.True("abc".Contains("a"))` -> `Assert.Contains("a", "abc")`
`Assert.False("abc".Contains("d"))` -> `Assert.DoesNotContain("d", "abc")`
`Assert.True("abc".StartsWith("a"))` -> `Assert.StartsWith("a", "abc")`
`Assert.True("abc".EndsWith("c"))` -> `Assert.EndsWith("c", "abc")`

Also include overloads that take a `StringComparison`.

Do not suggest for `Assert.True/False` overloads that take a `userMessage` parameter. Maybe that should be a separate analyzer rule?

**Comment by bradwilson** [comment]
This issue was moved to xunit/xunit#1260
