### ISSUE TITLE
Analyzer for MemberDataAttribute

### ISSUE THREAD

**Issue by marcind** [xunit/xunit.analyzers#6]
Member specified by the attribute must be
- public
- static
- property, field, or method
- return something assignable to `IEnumerable<object[]>`
- if no `MemberType` specified, member must be available on test class (unless class of test method is abstract, see https://github.com/xunit/xunit/pull/967)
- if property, getter must be public
- if method, parameters specified in attribute must be assignable to method parameters, and their count must match

This should probably be different rules, depending on implementation complexity

**Comment by bradwilson** [comment]
This issue was moved to xunit/xunit#1243
